### ISSUE TITLE
v1.0 checklist

### ISSUE THREAD

**Issue by pastudan** [create-node/create-node-app#6]
- [x] Ensure that metamodules can be deployed locally via docker-compose and in production to Kubernetes using `yarn deploy`
- [x] add an easy mechanism for adding metamodules to a project, ie `yarn metamodule add redis` or `yarn app add redis`
- [x] Ensure that driver files get placed into the app in the correct place
- [x] (DNA) Expose App / UI on KubeSail
  - [x] expose APP natively -or-
  - [x] proxy_pass /api routes to API on UI container
- [x] check for kubectl >= 1.14

optional / cleanup:
- [x] Use single dockerfile / image with separate entrypoints

**Comment by sheerun** [comment]
Maybe db migration toolkit? I recommend [knex](http://knexjs.org/) and [knex-migrate](https://github.com/sheerun/knex-migrate)

**Comment by pastudan** [comment]
@sheerun Apologies -- just now seeing this! Agreed that a migration tool would be useful, but we wanted to avoid being too opinionated on DB tools. That's why our [postgres metamodule](https://github.com/metamodules/postgres) includes only the postgres driver, but still allows you to add an ORM like knex on top.

Closing this issues since these tasks have all been completed and v1 has been released for quite some time.
